/* CVS $Id: $ */
package com.kasabi.labs.vocabularies; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from cheese.ttl 
 * @author Auto-generated by schemagen on 20 Dec 2011 12:07 
 */
public class CHEESE {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://data.kasabi.com/dataset/cheese/schema/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property aging = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/aging" );
    
    public static final Property certification = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/certification" );
    
    public static final Property country = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/country" );
    
    public static final Property diameter = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/diameter" );
    
    public static final Property height = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/height" );
    
    public static final Property location = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/location" );
    
    public static final Property milkProcessing = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/milkProcessing" );
    
    public static final Property milkSource = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/milkSource" );
    
    public static final Property milkType = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/milkType" );
    
    public static final Property municipality = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/municipality" );
    
    public static final Property province = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/province" );
    
    public static final Property region = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/region" );
    
    public static final Property shape = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/shape" );
    
    public static final Property texture = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/texture" );
    
    public static final Property use = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/use" );
    
    public static final Property weight = m_model.createProperty( "http://data.kasabi.com/dataset/cheese/schema/weight" );
    
    public static final Resource AgingPeriod = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/AgingPeriod" );
    
    public static final Resource BuffaloMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/BuffaloMilk" );
    
    public static final Resource Cheese = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Cheese" );
    
    public static final Resource CheeseProduction = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/CheeseProduction" );
    
    public static final Resource CheeseTexture = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/CheeseTexture" );
    
    public static final Resource CheeseUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/CheeseUse" );
    
    public static final Resource CookingUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/CookingUse" );
    
    public static final Resource Country = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Country" );
    
    public static final Resource CowMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/CowMilk" );
    
    public static final Resource FreshCheese = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/FreshCheese" );
    
    public static final Resource GeographicalIndication = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/GeographicalIndication" );
    
    public static final Resource GoatMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/GoatMilk" );
    
    public static final Resource GratingUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/GratingUse" );
    
    public static final Resource GrillingUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/GrillingUse" );
    
    public static final Resource HardCheese = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/HardCheese" );
    
    public static final Resource Location = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Location" );
    
    public static final Resource MeltingUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/MeltingUse" );
    
    public static final Resource Milk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Milk" );
    
    public static final Resource MilkProcessing = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/MilkProcessing" );
    
    public static final Resource MilkSource = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/MilkSource" );
    
    public static final Resource MilkType = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/MilkType" );
    
    public static final Resource MixedMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/MixedMilk" );
    
    public static final Resource Municipality = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Municipality" );
    
    public static final Resource PastourizedMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/PastourizedMilk" );
    
    public static final Resource Province = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Province" );
    
    public static final Resource RawMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/RawMilk" );
    
    public static final Resource Region = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/Region" );
    
    public static final Resource SemiHardCheese = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/SemiHardCheese" );
    
    public static final Resource SemiSkimmedMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/SemiSkimmedMilk" );
    
    public static final Resource SheepMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/SheepMilk" );
    
    public static final Resource SkimmedMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/SkimmedMilk" );
    
    public static final Resource SoftCheese = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/SoftCheese" );
    
    public static final Resource SpreadingUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/SpreadingUse" );
    
    public static final Resource TableUse = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/TableUse" );
    
    public static final Resource VeryHardCheese = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/VeryHardCheese" );
    
    public static final Resource WholeMilk = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/WholeMilk" );
    
    public static final Resource PDO = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/PDO" );
    
    public static final Resource PGI = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/PGI" );
    
    public static final Resource TSG = m_model.createResource( "http://data.kasabi.com/dataset/cheese/schema/TSG" );
    
}
